name: aeson
version: 2.1.0.0
id: aeson-2.1.0.0-BPcfA4w4Nus1eTOz7Rskqk
key: aeson-2.1.0.0-BPcfA4w4Nus1eTOz7Rskqk
license: BSD-3-Clause
copyright: (c) 2011-2016 Bryan O'Sullivan
           (c) 2011 MailRank, Inc.
maintainer: Adam Bergmark <adam@bergmark.nl>
author: Bryan O'Sullivan <bos@serpentine.com>
stability: experimental
homepage: https://github.com/haskell/aeson
synopsis: Fast JSON parsing and encoding
description:
    A JSON parsing and encoding library optimized for ease of use
    and high performance.
    .
    To get started, see the documentation for the @Data.Aeson@ module
    below.
    .
    (A note on naming: in Greek mythology, Aeson was the father of Jason.)
category: Text, Web, JSON
abi: f81245c62d05a814665af3b60b90b551
exposed: True
exposed-modules:
    Data.Aeson Data.Aeson.Encoding Data.Aeson.Encoding.Internal
    Data.Aeson.Internal Data.Aeson.Internal.Time Data.Aeson.Key
    Data.Aeson.KeyMap Data.Aeson.Parser Data.Aeson.Parser.Internal
    Data.Aeson.QQ.Simple Data.Aeson.TH Data.Aeson.Text Data.Aeson.Types
hidden-modules: Data.Aeson.Encoding.Builder
                Data.Aeson.Internal.ByteString Data.Aeson.Internal.Functions
                Data.Aeson.Internal.Text Data.Aeson.Internal.TH
                Data.Aeson.Parser.Time Data.Aeson.Parser.Unescape
                Data.Aeson.Types.Class Data.Aeson.Types.FromJSON
                Data.Aeson.Types.Generic Data.Aeson.Types.Internal
                Data.Aeson.Types.ToJSON Data.Attoparsec.Time
                Data.Attoparsec.Time.Internal Data.Aeson.Parser.UnescapePure
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/aeson-2.1.0.0-BPcfA4w4Nus1eTOz7Rskqk
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/aeson-2.1.0.0-BPcfA4w4Nus1eTOz7Rskqk
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/aeson-2.1.0.0
hs-libraries: HSaeson-2.1.0.0-BPcfA4w4Nus1eTOz7Rskqk
depends:
    OneTuple-0.3.1-K2rUJtkopj92fEvfp0a161
    QuickCheck-2.14.2-HhJDZwL6ynQE82OF2g896M
    attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA base-4.12.0.0
    base-compat-batteries-0.12.1-D7QtK6CF7649gZvXZZvACX
    bytestring-0.10.8.2 containers-0.6.0.1
    data-fix-0.3.2-CdLfeNawC8vGbAW8HSq1G8 deepseq-1.4.4.0
    dlist-1.0-8ucnnb0hbDW4h0jIaV7sfW
    generically-0.1-8PCfV20eXmeB05FdtsYNmu ghc-prim-0.5.3
    hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
    indexed-traversable-0.1.2-9akKdFoyxR68aS3W4yhwtK
    primitive-0.7.4.0-1Rfl9qw09JFC15XGax024S
    scientific-0.3.7.0-D8ke528voluIWIdu6neXQI
    semialign-1.2.0.1-C7RP9WpGQ9OB7UHnwWg8ur
    strict-0.4.0.1-GkMACwQb4VaC4ZYaCmkzB
    tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV template-haskell-2.14.0.0
    text-1.2.3.1 text-short-0.1.5-L2vAZSaqchDGijQgktXZLo
    th-abstraction-0.4.4.0-B7ShXiDIestFui7hwhuBOt
    these-1.1.1.1-EQ8nL5dWErsDKWbRRBDo8k time-1.8.0.2
    time-compat-1.9.6.1-FS5szJ4ugY57dRKe0Y5K9Q
    unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
    uuid-types-1.0.5-JC6l3EtANxFL1BWuOFs09f
    vector-0.13.0.0-EY1ezPeV6x5EBOONBzdfse
    witherable-0.4.2-FTJsoTFWi6bKd5fGuW0R8
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/aeson-2.1.0.0/html/aeson.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/aeson-2.1.0.0/html
