name: ansi-terminal
version: 0.11.3
id: ansi-terminal-0.11.3-Iax9HN5nUILCdJnXzolubX
key: ansi-terminal-0.11.3-Iax9HN5nUILCdJnXzolubX
license: BSD-3-Clause
maintainer: Mike Pilgrem <public@pilgrem.com>, Roman Cheplyaka <roma@ro-che.info>
author: Max Bolingbroke
homepage: https://github.com/UnkindPartition/ansi-terminal
synopsis: Simple ANSI terminal support, with Windows compatibility
description:
    ANSI terminal support for Haskell: allows cursor movement,
    screen clearing, color output, showing or hiding the
    cursor, and changing the title. Works on UNIX and Windows.
category: User Interfaces
abi: 3bed8217e2669722641c31b6a56d7ee1
exposed: True
exposed-modules:
    System.Console.ANSI System.Console.ANSI.Codes
    System.Console.ANSI.Types
hidden-modules: System.Console.ANSI.Unix
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/ansi-terminal-0.11.3-Iax9HN5nUILCdJnXzolubX
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/ansi-terminal-0.11.3-Iax9HN5nUILCdJnXzolubX
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/ansi-terminal-0.11.3
hs-libraries: HSansi-terminal-0.11.3-Iax9HN5nUILCdJnXzolubX
depends:
    base-4.12.0.0 colour-2.3.5-y0xjV3ONUd40VuBtReEvC
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/ansi-terminal-0.11.3/html/ansi-terminal.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/ansi-terminal-0.11.3/html
