name: asn1-types
version: 0.3.4
id: asn1-types-0.3.4-9ZanhAv4Z4RCTU4won7URP
key: asn1-types-0.3.4-9ZanhAv4Z4RCTU4won7URP
license: BSD-3-Clause
copyright: Vincent Hanquez <vincent@snarc.org>
maintainer: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
stability: experimental
homepage: http://github.com/vincenthz/hs-asn1
synopsis: ASN.1 types
description:
    ASN.1 standard types
category: Data
abi: b5c18b69e1db55a810edf726f251ddbe
exposed: True
exposed-modules:
    Data.ASN1.BitArray Data.ASN1.OID Data.ASN1.Pretty Data.ASN1.Types
    Data.ASN1.Types.Lowlevel Data.ASN1.Types.String
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/asn1-types-0.3.4-9ZanhAv4Z4RCTU4won7URP
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/asn1-types-0.3.4-9ZanhAv4Z4RCTU4won7URP
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/asn1-types-0.3.4
hs-libraries: HSasn1-types-0.3.4-9ZanhAv4Z4RCTU4won7URP
depends:
    base-4.12.0.0 bytestring-0.10.8.2
    hourglass-0.2.12-333qxqQQ3eK9Jo0nKcpgW5
    memory-0.17.0-B4oCfvxykobLSIFpq5HVDY
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/asn1-types-0.3.4/html/asn1-types.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/asn1-types-0.3.4/html
