name: assoc
version: 1.0.2
id: assoc-1.0.2-D7MedFChUIVKUi69UXhFjR
key: assoc-1.0.2-D7MedFChUIVKUi69UXhFjR
license: BSD-3-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
author: Oleg Grenrus <oleg.grenrus@iki.fi>
synopsis: swap and assoc: Symmetric and Semigroupy Bifunctors
description:
    Provides generalisations of
    @swap :: (a,b) -> (b,a)@ and
    @assoc :: ((a,b),c) -> (a,(b,c))@
    to
    @Bifunctor@s supporting similar operations (e.g. @Either@, @These@).
category: Data
abi: 59f25229ab45e67b3deac9df344e5d28
exposed: True
exposed-modules:
    Data.Bifunctor.Assoc Data.Bifunctor.Swap
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/assoc-1.0.2-D7MedFChUIVKUi69UXhFjR
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/assoc-1.0.2-D7MedFChUIVKUi69UXhFjR
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/assoc-1.0.2
hs-libraries: HSassoc-1.0.2-D7MedFChUIVKUi69UXhFjR
depends:
    base-4.12.0.0 bifunctors-5.5.12-1PJnXEmM40dBS6Myee13SP
    tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/assoc-1.0.2/html/assoc.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/assoc-1.0.2/html
