name: z-attoparsec-z-attoparsec-internal
version: 0.14.4
package-name: attoparsec
lib-name: attoparsec-internal
id: attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA-attoparsec-internal
key: attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA-attoparsec-internal
license: BSD-3-Clause
maintainer: Bryan O'Sullivan <bos@serpentine.com>, Ben Gamari <ben@smart-cactus.org>
author: Bryan O'Sullivan <bos@serpentine.com>
stability: experimental
homepage: https://github.com/bgamari/attoparsec
synopsis: Fast combinator parsing for bytestrings and text
description:
    A fast parser combinator library, aimed particularly at dealing
    efficiently with network protocols and complicated text/binary
    file formats.
category: Text, Parsing
abi: fc6bb6369bf58afcece159b521170044
exposed-modules:
    Data.Attoparsec.ByteString.Buffer
    Data.Attoparsec.ByteString.FastSet Data.Attoparsec.Internal.Compat
    Data.Attoparsec.Internal.Fhthagn Data.Attoparsec.Text.Buffer
    Data.Attoparsec.Text.FastSet
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4
hs-libraries: HSattoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA-attoparsec-internal
depends:
    array-0.5.3.0 base-4.12.0.0 bytestring-0.10.8.2 text-1.2.3.1
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4/html/attoparsec.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4/html
