name: attoparsec
version: 0.14.4
id: attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
key: attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
license: BSD-3-Clause
maintainer: Bryan O'Sullivan <bos@serpentine.com>, Ben Gamari <ben@smart-cactus.org>
author: Bryan O'Sullivan <bos@serpentine.com>
stability: experimental
homepage: https://github.com/bgamari/attoparsec
synopsis: Fast combinator parsing for bytestrings and text
description:
    A fast parser combinator library, aimed particularly at dealing
    efficiently with network protocols and complicated text/binary
    file formats.
category: Text, Parsing
abi: 3ac502c3c5f4291b17adc82c4c8ba944
exposed: True
exposed-modules:
    Data.Attoparsec Data.Attoparsec.ByteString
    Data.Attoparsec.ByteString.Char8 Data.Attoparsec.ByteString.Lazy
    Data.Attoparsec.Char8 Data.Attoparsec.Combinator
    Data.Attoparsec.Internal Data.Attoparsec.Internal.Types
    Data.Attoparsec.Lazy Data.Attoparsec.Number Data.Attoparsec.Text
    Data.Attoparsec.Text.Lazy Data.Attoparsec.Types
    Data.Attoparsec.Zepto
hidden-modules: Data.Attoparsec.ByteString.Internal
                Data.Attoparsec.Text.Internal
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4
hs-libraries: HSattoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
depends:
    array-0.5.3.0
    attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA-attoparsec-internal
    base-4.12.0.0 bytestring-0.10.8.2 containers-0.6.0.1
    deepseq-1.4.4.0 ghc-prim-0.5.3
    scientific-0.3.7.0-D8ke528voluIWIdu6neXQI text-1.2.3.1
    transformers-0.5.6.2
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4/html/attoparsec.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/attoparsec-0.14.4/html
