name: basement
version: 0.0.13
id: basement-0.0.13-HlswQ9Mtqty4GpnQjRdfKt
key: basement-0.0.13-HlswQ9Mtqty4GpnQjRdfKt
license: BSD-3-Clause
copyright: 2015-2017 Vincent Hanquez <vincent@snarc.org>
           , 2017-2018 Foundation Maintainers
maintainer: vincent@snarc.org
homepage: https://github.com/haskell-foundation/foundation#readme
synopsis: Foundation scrap box of array & string
description:
    Foundation most basic primitives without any dependencies
category: Web
abi: 14f6d94d9ecf1c9c959e8e83f02ab045
exposed: True
exposed-modules:
    Basement.Alg.XorShift Basement.Base16 Basement.Bindings.Memory
    Basement.Bits Basement.Block Basement.Block.Builder
    Basement.Block.Mutable Basement.BlockN Basement.Bounded
    Basement.BoxedArray Basement.Cast Basement.Compat.AMP
    Basement.Compat.Base Basement.Compat.Bifunctor
    Basement.Compat.C.Types Basement.Compat.CallStack
    Basement.Compat.ExtList Basement.Compat.Identity
    Basement.Compat.IsList Basement.Compat.MonadTrans
    Basement.Compat.Natural Basement.Compat.NumLiteral
    Basement.Compat.PrimTypes Basement.Compat.Primitive
    Basement.Compat.Semigroup Basement.Compat.Typeable
    Basement.Endianness Basement.Environment Basement.Exception
    Basement.FinalPtr Basement.Floating Basement.From Basement.Imports
    Basement.IntegralConv Basement.Monad Basement.MutableBuilder
    Basement.Nat Basement.NonEmpty Basement.NormalForm
    Basement.Numerical.Additive Basement.Numerical.Multiplicative
    Basement.Numerical.Number Basement.Numerical.Subtractive
    Basement.PrimType Basement.Sized.Block Basement.Sized.List
    Basement.Sized.UVect Basement.Sized.Vect Basement.String
    Basement.String.Builder Basement.Terminal Basement.Terminal.ANSI
    Basement.These Basement.Types.AsciiString Basement.Types.Char7
    Basement.Types.CharUTF8 Basement.Types.OffsetSize
    Basement.Types.Ptr Basement.Types.Word128 Basement.Types.Word256
    Basement.UArray Basement.UArray.Mutable
hidden-modules: Basement.Error Basement.Show Basement.Runtime
                Basement.Alg.Class Basement.Alg.Mutable Basement.Alg.PrimArray
                Basement.Alg.UTF8 Basement.Alg.String Basement.Numerical.Conversion
                Basement.Block.Base Basement.UTF8.Base Basement.UTF8.Helper
                Basement.UTF8.Table Basement.UTF8.Types Basement.UArray.Base
                Basement.String.CaseMapping Basement.String.Encoding.Encoding
                Basement.String.Encoding.UTF16 Basement.String.Encoding.UTF32
                Basement.String.Encoding.ASCII7 Basement.String.Encoding.ISO_8859_1
                Basement.Terminal.Size
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/basement-0.0.13-HlswQ9Mtqty4GpnQjRdfKt
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/basement-0.0.13-HlswQ9Mtqty4GpnQjRdfKt
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/basement-0.0.13
hs-libraries: HSbasement-0.0.13-HlswQ9Mtqty4GpnQjRdfKt
depends:
    base-4.12.0.0 ghc-prim-0.5.3
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/basement-0.0.13/html/basement.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/basement-0.0.13/html
