name: blaze-markup
version: 0.8.2.8
id: blaze-markup-0.8.2.8-La34AetGdrgBfbDxaNOhLH
key: blaze-markup-0.8.2.8-La34AetGdrgBfbDxaNOhLH
license: BSD-3-Clause
maintainer: Jasper Van der Jeugt <m@jaspervdj.be>
author: Jasper Van der Jeugt, Simon Meier, Deepak Jois
stability: Experimental
homepage: http://jaspervdj.be/blaze
synopsis: A blazingly fast markup combinator library for Haskell
description:
    Core modules of a blazingly fast markup combinator library for the Haskell
    programming language. The Text.Blaze module is a good
    starting point, as well as this tutorial:
    <http://jaspervdj.be/blaze/tutorial.html>.
category: Text
abi: def412dd0bde0a462a706d617da863e6
exposed: True
exposed-modules:
    Text.Blaze Text.Blaze.Internal Text.Blaze.Renderer.Pretty
    Text.Blaze.Renderer.String Text.Blaze.Renderer.Text
    Text.Blaze.Renderer.Utf8
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/blaze-markup-0.8.2.8-La34AetGdrgBfbDxaNOhLH
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/blaze-markup-0.8.2.8-La34AetGdrgBfbDxaNOhLH
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/blaze-markup-0.8.2.8
hs-libraries: HSblaze-markup-0.8.2.8-La34AetGdrgBfbDxaNOhLH
depends:
    base-4.12.0.0 blaze-builder-0.4.2.2-4zsxR3LFhmJDaKWUGXRU7O
    bytestring-0.10.8.2 text-1.2.3.1
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/blaze-markup-0.8.2.8/html/blaze-markup.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/blaze-markup-0.8.2.8/html
