name: boring
version: 0.2
id: boring-0.2-jRSseOtWcADurKGKXyqM1
key: boring-0.2-jRSseOtWcADurKGKXyqM1
license: BSD-3-Clause
copyright: (c) 2017-2021 Oleg Grenrus
maintainer: Oleg.Grenrus <oleg.grenrus@iki.fi>
author: Oleg Grenrus <oleg.grenrus@iki.fi>
homepage: https://github.com/phadej/boring
synopsis: Boring and Absurd types
description:
    * @Boring@ types are isomorphic to @()@.
    .
    * @Absurd@ types are isomorphic to @Void@.
    .
    See [What does () mean in Haskell -answer by Conor McBride](https://stackoverflow.com/questions/33112439/what-does-mean-in-haskell/33115522#33115522)
category: Data
abi: d7b0a585bbc1ceee7ac7415ea9946c75
exposed: True
exposed-modules:
    Data.Boring
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/boring-0.2-jRSseOtWcADurKGKXyqM1
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/boring-0.2-jRSseOtWcADurKGKXyqM1
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/boring-0.2
hs-libraries: HSboring-0.2-jRSseOtWcADurKGKXyqM1
depends:
    base-4.12.0.0 tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
    transformers-0.5.6.2
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/boring-0.2/html/boring.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/boring-0.2/html
