name: data-fix
version: 0.3.2
id: data-fix-0.3.2-CdLfeNawC8vGbAW8HSq1G8
key: data-fix-0.3.2-CdLfeNawC8vGbAW8HSq1G8
license: BSD-3-Clause
maintainer: <anton.kholomiov@gmail.com>
author: Anton Kholomiov, Edward Kmett, Oleg Grenrus
stability: Experimental
homepage: https://github.com/spell-music/data-fix
synopsis: Fixpoint data types
description:
    Fixpoint types and recursion schemes. If you define your AST as
    fixpoint type, you get fold and unfold operations for free.
    .
    Thanks for contribution to: Matej Kollar, Herbert Valerio Riedel
category: Data
abi: 2a61dbdab33501039bdd67ae29131260
exposed: True
exposed-modules:
    Data.Fix
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/data-fix-0.3.2-CdLfeNawC8vGbAW8HSq1G8
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/data-fix-0.3.2-CdLfeNawC8vGbAW8HSq1G8
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/data-fix-0.3.2
hs-libraries: HSdata-fix-0.3.2-CdLfeNawC8vGbAW8HSq1G8
depends:
    base-4.12.0.0 deepseq-1.4.4.0
    hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/data-fix-0.3.2/html/data-fix.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/data-fix-0.3.2/html
