name: dec
version: 0.0.4
id: dec-0.0.4-DJjVhjl2l8FAf23A5A9cLw
key: dec-0.0.4-DJjVhjl2l8FAf23A5A9cLw
license: BSD-3-Clause
copyright: (c) 2019-2021 Oleg Grenrus
maintainer: Oleg.Grenrus <oleg.grenrus@iki.fi>
author: Oleg Grenrus <oleg.grenrus@iki.fi>
homepage: https://github.com/phadej/vec
synopsis: Decidable propositions.
description:
    This package provides a @Dec@ type.
    .
    @
    type Neg a = a -> Void
    .
    data Dec a
    \    = Yes a
    \    | No (Neg a)
    @
category: Data, Dependent Types
abi: 6913ca9cef74668ed33cf50daf7da850
exposed: True
exposed-modules:
    Data.Type.Dec
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/dec-0.0.4-DJjVhjl2l8FAf23A5A9cLw
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/dec-0.0.4-DJjVhjl2l8FAf23A5A9cLw
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/dec-0.0.4
hs-libraries: HSdec-0.0.4-DJjVhjl2l8FAf23A5A9cLw
depends:
    base-4.12.0.0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/dec-0.0.4/html/dec.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/dec-0.0.4/html
