name: expiring-cache-map
version: 0.0.6.1
id: expiring-cache-map-0.0.6.1-GdrXUtOMqMtLKBBJSzdXwP
key: expiring-cache-map-0.0.6.1-GdrXUtOMqMtLKBBJSzdXwP
license: BSD-3-Clause
copyright: (c) 2014 Edward L. Blake
maintainer: edwardlblake@gmail.com
author: Edward L. Blake
homepage: https://codeberg.org/elblake/expiring-cache-map
synopsis: General purpose simple caching.
description:
    A simple general purpose shared state cache map with automatic expiration
    of values, for caching the results of accessing a resource such as reading
    a file. With variations for Ord and Hashable keys using "Data.Map.Strict"
    and "Data.HashMap.Strict", respectively.
category: Caching
abi: ebc618f1c82f989accbed296d80e86e8
exposed: True
exposed-modules:
    Caching.ExpiringCacheMap.HashECM
    Caching.ExpiringCacheMap.Internal.Internal
    Caching.ExpiringCacheMap.Internal.Types
    Caching.ExpiringCacheMap.OrdECM Caching.ExpiringCacheMap.Types
    Caching.ExpiringCacheMap.Utils.TestSequence
    Caching.ExpiringCacheMap.Utils.Types
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/expiring-cache-map-0.0.6.1-GdrXUtOMqMtLKBBJSzdXwP
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/expiring-cache-map-0.0.6.1-GdrXUtOMqMtLKBBJSzdXwP
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/expiring-cache-map-0.0.6.1
hs-libraries: HSexpiring-cache-map-0.0.6.1-GdrXUtOMqMtLKBBJSzdXwP
depends:
    base-4.12.0.0 containers-0.6.0.1
    hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
    unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/expiring-cache-map-0.0.6.1/html/expiring-cache-map.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/expiring-cache-map-0.0.6.1/html
