name: generically
version: 0.1
id: generically-0.1-8PCfV20eXmeB05FdtsYNmu
key: generically-0.1-8PCfV20eXmeB05FdtsYNmu
license: BSD-3-Clause
copyright: 2022 Oleg Grenrus
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
author: Oleg Grenrus
synopsis: Generically newtype to use with DerivingVia
description:
    This is a compatibility package as @Generically@ and @Generically1@ newtypes
    are available since @base-4.17@ in 'GHC.Generics'.
category: Generics
abi: 31f1625c5a7ecb5cca8a735d84e437de
exposed: True
exposed-modules:
    GHC.Generics.Generically
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/generically-0.1-8PCfV20eXmeB05FdtsYNmu
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/generically-0.1-8PCfV20eXmeB05FdtsYNmu
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/generically-0.1
hs-libraries: HSgenerically-0.1-8PCfV20eXmeB05FdtsYNmu
depends:
    base-4.12.0.0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/generically-0.1/html/generically.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/generically-0.1/html
