name: http-types
version: 0.12.3
id: http-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
key: http-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
license: BSD-3-Clause
copyright: (C) 2011 Aristid Breitkreuz
maintainer: aristidb@googlemail.com
author: Aristid Breitkreuz, Michael Snoyman
homepage: https://github.com/aristidb/http-types
synopsis: Generic HTTP types for Haskell (for both client and server code).
description:
    Generic HTTP types for Haskell (for both client and server code).
category: Network, Web
abi: 91e71798edfad1f156a33abc02e45a8f
exposed: True
exposed-modules:
    Network.HTTP.Types Network.HTTP.Types.Header
    Network.HTTP.Types.Method Network.HTTP.Types.QueryLike
    Network.HTTP.Types.Status Network.HTTP.Types.URI
    Network.HTTP.Types.Version
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/http-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/http-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/http-types-0.12.3
hs-libraries: HShttp-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
depends:
    array-0.5.3.0 base-4.12.0.0 bytestring-0.10.8.2
    case-insensitive-1.2.1.0-GFogpon08FP3uiOMpnCrG3 text-1.2.3.1
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/http-types-0.12.3/html/http-types.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/http-types-0.12.3/html
