name: http-date
version: 0.0.11
id: http-date-0.0.11-KviULUeBaxoxCjoIQXxrL
key: http-date-0.0.11-KviULUeBaxoxCjoIQXxrL
license: BSD-3-Clause
maintainer: Kazu Yamamoto <kazu@iij.ad.jp>
author: Kazu Yamamoto <kazu@iij.ad.jp>
synopsis: HTTP Date parser/formatter
description:
    Fast parser and formatter for HTTP Date
category: Network, Web
abi: d80db4d8fe2aaafa5a9b50b0615d3991
exposed: True
exposed-modules:
    Network.HTTP.Date
hidden-modules: Network.HTTP.Date.Converter
                Network.HTTP.Date.Formatter Network.HTTP.Date.Types
                Network.HTTP.Date.Parser
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/http-date-0.0.11-KviULUeBaxoxCjoIQXxrL
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/http-date-0.0.11-KviULUeBaxoxCjoIQXxrL
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/http-date-0.0.11
hs-libraries: HShttp-date-0.0.11-KviULUeBaxoxCjoIQXxrL
depends:
    array-0.5.3.0 attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
    base-4.12.0.0 bytestring-0.10.8.2 time-1.8.0.2
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/http-date-0.0.11/html/http-date.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/http-date-0.0.11/html
