name: http2
version: 3.0.3
id: http2-3.0.3-HCJgRf3JClSJVuh1KdayG2
key: http2-3.0.3-HCJgRf3JClSJVuh1KdayG2
license: BSD-3-Clause
maintainer: Kazu Yamamoto <kazu@iij.ad.jp>
author: Kazu Yamamoto <kazu@iij.ad.jp>
homepage: https://github.com/kazu-yamamoto/http2
synopsis: HTTP/2 library
description:
    HTTP/2 library including frames, priority queues, HPACK, client and server.
category: Network
abi: 423d75eef27e0b29ac94c9936de7403b
exposed: True
exposed-modules:
    Network.HPACK Network.HPACK.Internal Network.HPACK.Table
    Network.HPACK.Token Network.HTTP2 Network.HTTP2.Client
    Network.HTTP2.Client.Internal Network.HTTP2.Frame
    Network.HTTP2.Internal Network.HTTP2.Priority
    Network.HTTP2.Priority.Internal Network.HTTP2.Server
    Network.HTTP2.Server.Internal
hidden-modules: Imports Network.HPACK.Builder
                Network.HTTP2.Client.Types Network.HTTP2.Client.Run
                Network.HPACK.HeaderBlock Network.HPACK.HeaderBlock.Decode
                Network.HPACK.HeaderBlock.Encode Network.HPACK.HeaderBlock.Integer
                Network.HPACK.Huffman Network.HPACK.Huffman.Bit
                Network.HPACK.Huffman.ByteString Network.HPACK.Huffman.Decode
                Network.HPACK.Huffman.Encode Network.HPACK.Huffman.Params
                Network.HPACK.Huffman.Table Network.HPACK.Huffman.Tree
                Network.HPACK.Table.Dynamic Network.HPACK.Table.Entry
                Network.HPACK.Table.RevIndex Network.HPACK.Table.Static
                Network.HPACK.Types Network.HTTP2.Arch Network.HTTP2.Arch.Cache
                Network.HTTP2.Arch.Config Network.HTTP2.Arch.Context
                Network.HTTP2.Arch.EncodeFrame Network.HTTP2.Arch.File
                Network.HTTP2.Arch.HPACK Network.HTTP2.Arch.Manager
                Network.HTTP2.Arch.Queue Network.HTTP2.Arch.Rate
                Network.HTTP2.Arch.ReadN Network.HTTP2.Arch.Receiver
                Network.HTTP2.Arch.Sender Network.HTTP2.Arch.Status
                Network.HTTP2.Arch.Stream Network.HTTP2.Arch.Types
                Network.HTTP2.Frame.Decode Network.HTTP2.Frame.Encode
                Network.HTTP2.Frame.Types Network.HTTP2.Priority.PSQ
                Network.HTTP2.Priority.Queue Network.HTTP2.Server.Run
                Network.HTTP2.Server.Types Network.HTTP2.Server.Worker
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/http2-3.0.3-HCJgRf3JClSJVuh1KdayG2
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/http2-3.0.3-HCJgRf3JClSJVuh1KdayG2
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/http2-3.0.3
hs-libraries: HShttp2-3.0.3-HCJgRf3JClSJVuh1KdayG2
depends:
    array-0.5.3.0 async-2.2.4-CJwYGeYVRDT9eMIFwbj4es base-4.12.0.0
    bytestring-0.10.8.2 case-insensitive-1.2.1.0-GFogpon08FP3uiOMpnCrG3
    containers-0.6.0.1 http-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
    network-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW
    network-byte-order-0.1.6-4aZNEv2OmF511UFlR5VBHo
    psqueues-0.2.7.3-BCe1ErrJJhU4s4lYZsHP3h stm-2.5.0.0
    time-manager-0.0.0-13VNl63DGne4Q77KbSs6r9
    unix-time-0.4.7-59qhjWOWGlPC1MPvUtkKAw
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/http2-3.0.3/html/http2.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/http2-3.0.3/html
