name: http-api-data
version: 0.4.3
id: http-api-data-0.4.3-JKQnEEF5W0eK6NiW9Yss9f
key: http-api-data-0.4.3-JKQnEEF5W0eK6NiW9Yss9f
license: BSD-3-Clause
maintainer: Nickolay Kudasov <nickolay.kudasov@gmail.com>
author: Nickolay Kudasov <nickolay.kudasov@gmail.com>
stability: unstable
homepage: http://github.com/fizruk/http-api-data
synopsis: Converting to/from HTTP API data like URL pieces, headers and query parameters.
description:
    This package defines typeclasses used for converting Haskell data types to and from HTTP API data.
    .
    Please see README.md
category: Web
abi: 6d9d2791379accb1aa989ab418a4caed
exposed: True
exposed-modules:
    Web.FormUrlEncoded Web.HttpApiData Web.Internal.FormUrlEncoded
    Web.Internal.HttpApiData
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/http-api-data-0.4.3-JKQnEEF5W0eK6NiW9Yss9f
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/http-api-data-0.4.3-JKQnEEF5W0eK6NiW9Yss9f
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/http-api-data-0.4.3
hs-libraries: HShttp-api-data-0.4.3-JKQnEEF5W0eK6NiW9Yss9f
depends:
    attoparsec-0.14.4-GhL4hdJ15VdDriBu1YmDhA
    attoparsec-iso8601-1.0.2.1-1FLDrDWQuhOEi8J24VKn3t base-4.12.0.0
    base-compat-0.12.1-uMTPyxtbeC9sSYtBMSQfe bytestring-0.10.8.2
    containers-0.6.0.1 cookie-0.4.5-FViOMgoPVhL3PprTfOcJF2
    hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
    http-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
    tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV text-1.2.3.1
    time-compat-1.9.6.1-FS5szJ4ugY57dRKe0Y5K9Q transformers-0.5.6.2
    unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
    uuid-types-1.0.5-JC6l3EtANxFL1BWuOFs09f
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/http-api-data-0.4.3/html/http-api-data.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/http-api-data-0.4.3/html
