name: indexed-traversable-instances
version: 0.1.1
id: indexed-traversable-instances-0.1.1-uCyJVgG0I58WGFJhUChUG
key: indexed-traversable-instances-0.1.1-uCyJVgG0I58WGFJhUChUG
license: BSD-2-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
author: Edward Kmett
synopsis: More instances of FunctorWithIndex, FoldableWithIndex, TraversableWithIndex
description:
    This package provides extra instances for type-classes in the [indexed-traversable](https://hackage.haskell.org/package/indexed-traversable) package.
    .
    The intention is to keep this package minimal;
    it provides instances that formely existed in @lens@ or @optics-extra@.
    We recommend putting other instances directly into their defining packages.
    The @indexed-traversable@ package is light, having only GHC boot libraries
    as its dependencies.
category: Data
abi: ddb2f7ec22ce2cb34f7d68c34a5c1bf0
exposed: True
exposed-modules:
    Data.Functor.WithIndex.Instances
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/indexed-traversable-instances-0.1.1-uCyJVgG0I58WGFJhUChUG
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/indexed-traversable-instances-0.1.1-uCyJVgG0I58WGFJhUChUG
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/indexed-traversable-instances-0.1.1
hs-libraries: HSindexed-traversable-instances-0.1.1-uCyJVgG0I58WGFJhUChUG
depends:
    OneTuple-0.3.1-K2rUJtkopj92fEvfp0a161 base-4.12.0.0
    indexed-traversable-0.1.2-9akKdFoyxR68aS3W4yhwtK
    tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
    unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
    vector-0.13.0.0-EY1ezPeV6x5EBOONBzdfse
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/indexed-traversable-instances-0.1.1/html/indexed-traversable-instances.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/indexed-traversable-instances-0.1.1/html
