name: memory
version: 0.17.0
id: memory-0.17.0-B4oCfvxykobLSIFpq5HVDY
key: memory-0.17.0-B4oCfvxykobLSIFpq5HVDY
license: BSD-3-Clause
copyright: Vincent Hanquez <vincent@snarc.org>
maintainer: vincent@snarc.org, Nicolas Di Prima <nicolas@primetype.co.uk>
author: Vincent Hanquez <vincent@snarc.org>
stability: experimental
homepage: https://github.com/vincenthz/hs-memory
synopsis: memory and related abstraction stuff
description:
    Chunk of memory, polymorphic byte array management and manipulation
    .
    * A polymorphic byte array abstraction and function similar to strict ByteString.
    .
    * Different type of byte array abstraction.
    .
    * Raw memory IO operations (memory set, memory copy, ..)
    .
    * Aliasing with endianness support.
    .
    * Encoding : Base16, Base32, Base64.
    .
    * Hashing : FNV, SipHash
category: memory
abi: 76473b8c8b3cf48076869ce3136e6de6
exposed: True
exposed-modules:
    Data.ByteArray Data.ByteArray.Encoding Data.ByteArray.Hash
    Data.ByteArray.Mapping Data.ByteArray.Pack Data.ByteArray.Parse
    Data.ByteArray.Sized Data.Memory.Encoding.Base16
    Data.Memory.Encoding.Base32 Data.Memory.Encoding.Base64
    Data.Memory.Endian Data.Memory.ExtendedWords Data.Memory.PtrMethods
hidden-modules: Data.Memory.Internal.Compat
                Data.Memory.Internal.CompatPrim Data.Memory.Internal.CompatPrim64
                Data.Memory.Internal.DeepSeq Data.Memory.Internal.Imports
                Data.Memory.Hash.SipHash Data.Memory.Hash.FNV
                Data.ByteArray.Pack.Internal Data.ByteArray.Types
                Data.ByteArray.Bytes Data.ByteArray.ScrubbedBytes
                Data.ByteArray.Methods Data.ByteArray.MemView Data.ByteArray.View
                Data.Memory.MemMap.Posix
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/memory-0.17.0-B4oCfvxykobLSIFpq5HVDY
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/memory-0.17.0-B4oCfvxykobLSIFpq5HVDY
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/memory-0.17.0
hs-libraries: HSmemory-0.17.0-B4oCfvxykobLSIFpq5HVDY
depends:
    base-4.12.0.0 basement-0.0.13-HlswQ9Mtqty4GpnQjRdfKt
    bytestring-0.10.8.2 deepseq-1.4.4.0 ghc-prim-0.5.3
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/memory-0.17.0/html/memory.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/memory-0.17.0/html
