name: mmorph
version: 1.2.0
id: mmorph-1.2.0-ATDyH2c3txsL2y3eD4rbOs
key: mmorph-1.2.0-ATDyH2c3txsL2y3eD4rbOs
license: BSD-3-Clause
copyright: 2013 Gabriel Gonzalez
maintainer: Gabriel439@gmail.com
author: Gabriel Gonzalez
synopsis: Monad morphisms
description:
    This library provides monad morphism utilities, most commonly used
    for manipulating monad transformer stacks.
category: Control
abi: 5b72713fb019c4f8bd3eab7b7d8396ac
exposed: True
exposed-modules:
    Control.Monad.Morph Control.Monad.Trans.Compose
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/mmorph-1.2.0-ATDyH2c3txsL2y3eD4rbOs
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/mmorph-1.2.0-ATDyH2c3txsL2y3eD4rbOs
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/mmorph-1.2.0
hs-libraries: HSmmorph-1.2.0-ATDyH2c3txsL2y3eD4rbOs
depends:
    base-4.12.0.0 mtl-2.2.2 transformers-0.5.6.2
    transformers-compat-0.7.2-3DUcNPzv1ZaH0uINwDggMx
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/mmorph-1.2.0/html/mmorph.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/mmorph-1.2.0/html
