name: network
version: 3.1.2.7
id: network-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW
key: network-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW
license: BSD-3-Clause
maintainer: Kazu Yamamoto, Evan Borden
homepage: https://github.com/haskell/network
synopsis: Low-level networking interface
description:
    This package provides a low-level networking interface.
    .
    === High-Level Packages
    Other packages provide higher level interfaces:
    .
    * connection
    * hookup
    * network-simple
    .
    === Extended Packages
    @network@ seeks to provide a cross-platform core for networking. As such some
    APIs live in extended libraries. Packages in the @network@ ecosystem are
    often prefixed with @network-@.
    .
    ==== @network-bsd@
    In @network-3.0.0.0@ the @Network.BSD@ module was split off into its own
    package, @network-bsd-3.0.0.0@.
    .
    ==== @network-uri@
    In @network-2.6@ the @Network.URI@ module was split off into its own package,
    @network-uri-2.6@. If you're using the @Network.URI@ module you can
    automatically get it from the right package by adding this to your @.cabal@
    file:
    .
    > library
    >   build-depends: network-uri-flag
category: Network
abi: 3eadca03f252a41cad750063514a6d54
exposed: True
exposed-modules:
    Network.Socket Network.Socket.Address Network.Socket.ByteString
    Network.Socket.ByteString.Lazy Network.Socket.Internal
hidden-modules: Network.Socket.Buffer Network.Socket.ByteString.IO
                Network.Socket.ByteString.Internal Network.Socket.Cbits
                Network.Socket.Fcntl Network.Socket.Flag Network.Socket.Handle
                Network.Socket.If Network.Socket.Imports Network.Socket.Info
                Network.Socket.Name Network.Socket.Options Network.Socket.ReadShow
                Network.Socket.Shutdown Network.Socket.SockAddr
                Network.Socket.Syscall Network.Socket.Types Network.Socket.Unix
                Network.Socket.ByteString.Lazy.Posix Network.Socket.Posix.Cmsg
                Network.Socket.Posix.CmsgHdr Network.Socket.Posix.IOVec
                Network.Socket.Posix.MsgHdr
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/network-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/network-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/network-3.1.2.7
hs-libraries: HSnetwork-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW
include-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/network-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW/include
includes:
    HsNet.h HsNetDef.h alignment.h win32defs.h
depends:
    base-4.12.0.0 bytestring-0.10.8.2 deepseq-1.4.4.0 directory-1.3.3.0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/network-3.1.2.7/html/network.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/network-3.1.2.7/html
