name: old-locale
version: 1.0.0.7
id: old-locale-1.0.0.7-D4Rn5zPhtMJBwwirPJNu78
key: old-locale-1.0.0.7-D4Rn5zPhtMJBwwirPJNu78
license: BSD-3-Clause
maintainer: libraries@haskell.org
synopsis: locale library
description:
    This package provides the ability to adapt to
    locale conventions such as date and time formats.
category: System
abi: 05a9f79966ef30c42da7ad189eab0da9
exposed: True
exposed-modules:
    System.Locale
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/old-locale-1.0.0.7-D4Rn5zPhtMJBwwirPJNu78
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/old-locale-1.0.0.7-D4Rn5zPhtMJBwwirPJNu78
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/old-locale-1.0.0.7
hs-libraries: HSold-locale-1.0.0.7-D4Rn5zPhtMJBwwirPJNu78
depends:
    base-4.12.0.0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/old-locale-1.0.0.7/html/old-locale.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/old-locale-1.0.0.7/html
