name: pem
version: 0.2.4
id: pem-0.2.4-FKy7uuQJGwB11RGdRaLo5z
key: pem-0.2.4-FKy7uuQJGwB11RGdRaLo5z
license: BSD-3-Clause
copyright: Vincent Hanquez <vincent@snarc.org>
maintainer: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
stability: experimental
homepage: http://github.com/vincenthz/hs-pem
synopsis: Privacy Enhanced Mail (PEM) format reader and writer.
description:
    Privacy Enhanced Mail (PEM) format reader and writer. long description
category: Data
abi: b99105766045e16e99fde8d3024fcf4e
exposed: True
exposed-modules:
    Data.PEM
hidden-modules: Data.PEM.Parser Data.PEM.Writer Data.PEM.Types
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/pem-0.2.4-FKy7uuQJGwB11RGdRaLo5z
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/pem-0.2.4-FKy7uuQJGwB11RGdRaLo5z
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/pem-0.2.4
hs-libraries: HSpem-0.2.4-FKy7uuQJGwB11RGdRaLo5z
depends:
    base-4.12.0.0 basement-0.0.13-HlswQ9Mtqty4GpnQjRdfKt
    bytestring-0.10.8.2 memory-0.17.0-B4oCfvxykobLSIFpq5HVDY
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/pem-0.2.4/html/pem.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/pem-0.2.4/html
