name: resourcet
version: 1.2.6
id: resourcet-1.2.6-EfFQtCk1HnpItr2XuzVftj
key: resourcet-1.2.6-EfFQtCk1HnpItr2XuzVftj
license: BSD-3-Clause
maintainer: michael@snoyman.com
author: Michael Snoyman
homepage: http://github.com/snoyberg/conduit
synopsis: Deterministic allocation and freeing of scarce resources.
description:
    Hackage documentation generation is not reliable. For up to date documentation, please see: <http://www.stackage.org/package/resourcet>.
category: Data, Conduit
abi: 009f40b7aefd7b43456bb3b6ed9ea0cd
exposed: True
exposed-modules:
    Control.Monad.Trans.Resource Control.Monad.Trans.Resource.Internal
    Data.Acquire Data.Acquire.Internal UnliftIO.Resource
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/resourcet-1.2.6-EfFQtCk1HnpItr2XuzVftj
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/resourcet-1.2.6-EfFQtCk1HnpItr2XuzVftj
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/resourcet-1.2.6
hs-libraries: HSresourcet-1.2.6-EfFQtCk1HnpItr2XuzVftj
depends:
    base-4.12.0.0 containers-0.6.0.1
    exceptions-0.10.5-7XP095aUgezEztbzhlpLAr mtl-2.2.2
    primitive-0.7.4.0-1Rfl9qw09JFC15XGax024S transformers-0.5.6.2
    unliftio-core-0.2.0.1-Ks8Wj0PMnfXJ0tXeQNz1pB
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/resourcet-1.2.6/html/resourcet.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/resourcet-1.2.6/html
