name: semialign
version: 1.2.0.1
id: semialign-1.2.0.1-C7RP9WpGQ9OB7UHnwWg8ur
key: semialign-1.2.0.1-C7RP9WpGQ9OB7UHnwWg8ur
license: BSD-3-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
author: C. McCann, Oleg Grenrus
homepage: https://github.com/haskellari/these
synopsis: Align and Zip type-classes from the common Semialign ancestor.
description:
    The major use of @These@ of this is provided by the @align@ member of
    @Semialign@ class, representing a generalized notion of "zipping with padding"
    that combines structures without truncating to the size of the smaller input.
    .
    It turns out that @zip@ operation fits well the @Semialign@ class,
    forming lattice-like structure.
category: Data, These
abi: a6f2e0203f2b055cf416b6660ccacf57
exposed: True
exposed-modules:
    Data.Align Data.Crosswalk Data.Semialign Data.Semialign.Indexed
    Data.Zip
hidden-modules: Data.Semialign.Internal
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/semialign-1.2.0.1-C7RP9WpGQ9OB7UHnwWg8ur
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/semialign-1.2.0.1-C7RP9WpGQ9OB7UHnwWg8ur
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/semialign-1.2.0.1
hs-libraries: HSsemialign-1.2.0.1-C7RP9WpGQ9OB7UHnwWg8ur
depends:
    base-4.12.0.0 containers-0.6.0.1
    hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
    indexed-traversable-0.1.2-9akKdFoyxR68aS3W4yhwtK
    indexed-traversable-instances-0.1.1-uCyJVgG0I58WGFJhUChUG
    semigroupoids-5.3.7-BpE0uWym2wb8dCuP4VVdci
    tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
    these-1.1.1.1-EQ8nL5dWErsDKWbRRBDo8k transformers-0.5.6.2
    unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
    vector-0.13.0.0-EY1ezPeV6x5EBOONBzdfse
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/semialign-1.2.0.1/html/semialign.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/semialign-1.2.0.1/html
