name: simple-sendfile
version: 0.2.30
id: simple-sendfile-0.2.30-Gk9vw8aA9Lh1kdxCLYxbsr
key: simple-sendfile-0.2.30-Gk9vw8aA9Lh1kdxCLYxbsr
license: BSD-3-Clause
maintainer: Kazu Yamamoto <kazu@iij.ad.jp>
author: Kazu Yamamoto <kazu@iij.ad.jp>
synopsis: Cross platform library for the sendfile system call
description:
    Cross platform library for the sendfile system call.
    This library tries to call minimum system calls which
    are the bottleneck of web servers.
category: Network
abi: e3593d374131ca5494e6b3aeba59e4ba
exposed: True
exposed-modules:
    Network.Sendfile System.Linux.Sendfile
hidden-modules: Network.Sendfile.Types Network.Sendfile.Linux
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/simple-sendfile-0.2.30-Gk9vw8aA9Lh1kdxCLYxbsr
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/simple-sendfile-0.2.30-Gk9vw8aA9Lh1kdxCLYxbsr
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/simple-sendfile-0.2.30
hs-libraries: HSsimple-sendfile-0.2.30-Gk9vw8aA9Lh1kdxCLYxbsr
depends:
    base-4.12.0.0 bytestring-0.10.8.2
    network-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW unix-2.7.2.2
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/simple-sendfile-0.2.30/html/simple-sendfile.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/simple-sendfile-0.2.30/html
