name: singleton-bool
version: 0.1.6
id: singleton-bool-0.1.6-HzCy1k6co6V7pItJyN5ykd
key: singleton-bool-0.1.6-HzCy1k6co6V7pItJyN5ykd
license: BSD-3-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
author: Oleg Grenrus <oleg.grenrus@iki.fi>
homepage: https://github.com/phadej/singleton-bool#readme
synopsis: Type level booleans
description:
    Type level booleans.
    .
    @singletons@ package provides similar functionality,
    but it has tight dependency constraints.
category: Web
abi: b10b68f5f2cdcca643181651efc3cff6
exposed: True
exposed-modules:
    Data.Singletons.Bool
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/singleton-bool-0.1.6-HzCy1k6co6V7pItJyN5ykd
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/singleton-bool-0.1.6-HzCy1k6co6V7pItJyN5ykd
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/singleton-bool-0.1.6
hs-libraries: HSsingleton-bool-0.1.6-HzCy1k6co6V7pItJyN5ykd
depends:
    base-4.12.0.0 boring-0.2-jRSseOtWcADurKGKXyqM1
    dec-0.0.4-DJjVhjl2l8FAf23A5A9cLw deepseq-1.4.4.0
    some-1.0.4-DY62QlLy8XyINMVANfFxoS
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/singleton-bool-0.1.6/html/singleton-bool.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/singleton-bool-0.1.6/html
