name: some
version: 1.0.4
id: some-1.0.4-DY62QlLy8XyINMVANfFxoS
key: some-1.0.4-DY62QlLy8XyINMVANfFxoS
license: BSD-3-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
author: James Cook <mokus@deepbondi.net>, Oleg Grenrus <oleg.grenrus@iki.fi>
homepage: https://github.com/haskellari/some
synopsis: Existential type: Some
description:
    This library defines an existential type 'Some'.
    .
    @
    data Some f where
    \    Some :: f a -> Some f
    @
    .
    in few variants, and utilities to work with it.
    .
    If you are unsure which variant to use, use the one in "Data.Some" module.
category: Data, Dependent Types
abi: 19a158f8a18d88d063bed18036129aa0
exposed: True
exposed-modules:
    Data.GADT.Compare Data.GADT.DeepSeq Data.GADT.Show Data.Some
    Data.Some.Church Data.Some.GADT Data.Some.Newtype
hidden-modules: Data.GADT.Internal
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/some-1.0.4-DY62QlLy8XyINMVANfFxoS
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/some-1.0.4-DY62QlLy8XyINMVANfFxoS
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/some-1.0.4
hs-libraries: HSsome-1.0.4-DY62QlLy8XyINMVANfFxoS
depends:
    base-4.12.0.0 deepseq-1.4.4.0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/some-1.0.4/html/some.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/some-1.0.4/html
