name: sop-core
version: 0.5.0.2
id: sop-core-0.5.0.2-Fh6U7KDBEDjI4mvd3HlLI7
key: sop-core-0.5.0.2-Fh6U7KDBEDjI4mvd3HlLI7
license: BSD-3-Clause
maintainer: andres@well-typed.com
author: Edsko de Vries <edsko@well-typed.com>, Andres Löh <andres@well-typed.com>
synopsis: True Sums of Products
description:
    Implementation of n-ary sums and n-ary products.
    .
    The module "Data.SOP" is the main module of this library and contains
    more detailed documentation.
    .
    The main use case of this package is to serve as the core of
    @<https://hackage.haskell.org/package/generics-sop generics-sop>@.
    .
    A detailed description of the ideas behind this library is provided by
    the paper:
    .
    * Edsko de Vries and Andres Löh.
    <http://www.andres-loeh.de/TrueSumsOfProducts True Sums of Products>.
    Workshop on Generic Programming (WGP) 2014.
    .
category: Data
abi: 623da82f9ecf13b5cbebe56e8c8e216d
exposed: True
exposed-modules:
    Data.SOP Data.SOP.BasicFunctors Data.SOP.Classes
    Data.SOP.Constraint Data.SOP.Dict Data.SOP.NP Data.SOP.NS
    Data.SOP.Sing
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/sop-core-0.5.0.2-Fh6U7KDBEDjI4mvd3HlLI7
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/sop-core-0.5.0.2-Fh6U7KDBEDjI4mvd3HlLI7
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/sop-core-0.5.0.2
hs-libraries: HSsop-core-0.5.0.2-Fh6U7KDBEDjI4mvd3HlLI7
depends:
    base-4.12.0.0 deepseq-1.4.4.0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/sop-core-0.5.0.2/html/sop-core.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/sop-core-0.5.0.2/html
