name: string-conversions
version: 0.4.0.1
id: string-conversions-0.4.0.1-2f7URWpMHMH3wTdf3bSrH5
key: string-conversions-0.4.0.1-2f7URWpMHMH3wTdf3bSrH5
license: BSD-3-Clause
maintainer: soenkehahn@gmail.com
author: Sönke Hahn
homepage: https://github.com/soenkehahn/string-conversions#readme
synopsis: Simplifies dealing with different types for strings
description:
    Provides a simple type class for converting values of different string types into values of other string types.
category: Data
abi: 16a1dec790a3a4e2d35754eda67097ca
exposed: True
exposed-modules:
    Data.String.Conversions Data.String.Conversions.Monomorphic
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/string-conversions-0.4.0.1-2f7URWpMHMH3wTdf3bSrH5
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/string-conversions-0.4.0.1-2f7URWpMHMH3wTdf3bSrH5
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/string-conversions-0.4.0.1
hs-libraries: HSstring-conversions-0.4.0.1-2f7URWpMHMH3wTdf3bSrH5
depends:
    base-4.12.0.0 bytestring-0.10.8.2 text-1.2.3.1
    utf8-string-1.0.2-FP1EKCgJMgkB9n2B2eWYHr
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/string-conversions-0.4.0.1/html/string-conversions.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/string-conversions-0.4.0.1/html
