name: tagged
version: 0.8.6.1
id: tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
key: tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
license: BSD-3-Clause
copyright: 2009-2015 Edward A. Kmett
maintainer: Edward A. Kmett <ekmett@gmail.com>
author: Edward A. Kmett
stability: experimental
homepage: http://github.com/ekmett/tagged
synopsis: Haskell 98 phantom types to avoid unsafely passing dummy arguments
description:
    Haskell 98 phantom types to avoid unsafely passing dummy arguments.
category: Data, Phantom Types
abi: 4cac53d18998a879c4dea7e70ff71fb4
exposed: True
exposed-modules:
    Data.Proxy.TH Data.Tagged
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/tagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/tagged-0.8.6.1
hs-libraries: HStagged-0.8.6.1-61lWhBKHB5k4Sj4YQdMeSV
depends:
    base-4.12.0.0 deepseq-1.4.4.0 template-haskell-2.14.0.0
    transformers-0.5.6.2
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/tagged-0.8.6.1/html/tagged.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/tagged-0.8.6.1/html
