name: th-compat
version: 0.1.4
id: th-compat-0.1.4-Fe0A8gWrSfkC52saL8tfJp
key: th-compat-0.1.4-Fe0A8gWrSfkC52saL8tfJp
license: BSD-3-Clause
copyright: (C) 2020 Ryan Scott
maintainer: Ryan Scott <ryan.gl.scott@gmail.com>
author: Ryan Scott
homepage: https://github.com/haskell-compat/th-compat
synopsis: Backward- (and forward-)compatible Quote and Code types
description:
    This package defines a "Language.Haskell.TH.Syntax.Compat"
    module, which backports the @Quote@ and @Code@ types to
    work across a wide range of @template-haskell@ versions.
    The @makeRelativeToProject@ utility is also backported.
    On recent versions of @template-haskell@ (2.17.0.0 or
    later), this module simply reexports definitions
    from "Language.Haskell.TH.Syntax". Refer to the Haddocks
    for "Language.Haskell.TH.Syntax.Compat" for examples of
    how to use this module.
category: Text
abi: 28871991e1f876b44749831d64d1bd98
exposed: True
exposed-modules:
    Language.Haskell.TH.Syntax.Compat
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/th-compat-0.1.4-Fe0A8gWrSfkC52saL8tfJp
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/th-compat-0.1.4-Fe0A8gWrSfkC52saL8tfJp
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/th-compat-0.1.4
hs-libraries: HSth-compat-0.1.4-Fe0A8gWrSfkC52saL8tfJp
depends:
    base-4.12.0.0 directory-1.3.3.0 filepath-1.4.2.1
    template-haskell-2.14.0.0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/th-compat-0.1.4/html/th-compat.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/th-compat-0.1.4/html
