name: time-compat
version: 1.9.6.1
id: time-compat-1.9.6.1-FS5szJ4ugY57dRKe0Y5K9Q
key: time-compat-1.9.6.1-FS5szJ4ugY57dRKe0Y5K9Q
license: BSD-3-Clause
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
author: Ashley Yakeley
homepage: https://github.com/haskellari/time-compat
synopsis: Compatibility package for time
description:
    This packages tries to compat as much of @time@ features as possible.
    .
    /TODO:/
    .
    * Difference type @ParseTime@ and @FormatTime@ instances are missing.
    .
    * Formatting varies depending on underlying @time@ version
    .
    * @dayFractionToTimeOfDay@ on extreme values
category: Time, Compatibility
abi: c2df5de45fb1b27642ebfee59dfe5301
exposed: True
exposed-modules:
    Data.Time.Calendar.Compat Data.Time.Calendar.Easter.Compat
    Data.Time.Calendar.Julian.Compat Data.Time.Calendar.Month.Compat
    Data.Time.Calendar.MonthDay.Compat
    Data.Time.Calendar.OrdinalDate.Compat
    Data.Time.Calendar.Quarter.Compat
    Data.Time.Calendar.WeekDate.Compat Data.Time.Clock.Compat
    Data.Time.Clock.POSIX.Compat Data.Time.Clock.System.Compat
    Data.Time.Clock.TAI.Compat Data.Time.Compat Data.Time.Format.Compat
    Data.Time.Format.ISO8601.Compat Data.Time.LocalTime.Compat
hidden-modules: Data.Format Data.Time.Calendar.Private
                Data.Time.Calendar.Types Data.Time.Orphans
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/time-compat-1.9.6.1-FS5szJ4ugY57dRKe0Y5K9Q
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/time-compat-1.9.6.1-FS5szJ4ugY57dRKe0Y5K9Q
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/time-compat-1.9.6.1
hs-libraries: HStime-compat-1.9.6.1-FS5szJ4ugY57dRKe0Y5K9Q
depends:
    base-4.12.0.0 base-orphans-0.8.6-5O5jqEW3stE4CAsm1Catjq
    deepseq-1.4.4.0 hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
    time-1.8.0.2
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/time-compat-1.9.6.1/html/time-compat.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/time-compat-1.9.6.1/html
