name: unix-compat
version: 0.6
id: unix-compat-0.6-DsZOczkYwBC8eXogTONDW9
key: unix-compat-0.6-DsZOczkYwBC8eXogTONDW9
license: BSD-3-Clause
maintainer: Jacob Stanley <jacob@stanley.io>
author: Björn Bringert, Duncan Coutts, Jacob Stanley, Bryan O'Sullivan
homepage: http://github.com/jacobstanley/unix-compat
synopsis: Portable POSIX-compatibility layer.
description:
    This package provides portable implementations of parts
    of the unix package. This package re-exports the unix
    package when available. When it isn't available,
    portable implementations are used.
category: System
abi: aeb588b9a21ce0c7ec9d6d29beb8adca
exposed: True
exposed-modules:
    System.PosixCompat System.PosixCompat.Extensions
    System.PosixCompat.Files System.PosixCompat.Temp
    System.PosixCompat.Time System.PosixCompat.Types
    System.PosixCompat.Unistd System.PosixCompat.User
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/unix-compat-0.6-DsZOczkYwBC8eXogTONDW9
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/unix-compat-0.6-DsZOczkYwBC8eXogTONDW9
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/unix-compat-0.6
hs-libraries: HSunix-compat-0.6-DsZOczkYwBC8eXogTONDW9
include-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/unix-compat-0.6-DsZOczkYwBC8eXogTONDW9/include
includes:
    HsUnixCompat.h
depends:
    base-4.12.0.0 unix-2.7.2.2
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/unix-compat-0.6/html/unix-compat.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/unix-compat-0.6/html
