name: unordered-containers
version: 0.2.19.1
id: unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
key: unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
license: BSD-3-Clause
copyright: 2010-2014 Johan Tibell
           2010 Edward Z. Yang
maintainer: simon.jakobi@gmail.com, David.Feuer@gmail.com
author: Johan Tibell
homepage: https://github.com/haskell-unordered-containers/unordered-containers
synopsis: Efficient hashing-based container types
description:
    Efficient hashing-based container types.  The containers have been
    optimized for performance critical use, both in terms of large data
    quantities and high speed.
    .
    The declared cost of each operation is either worst-case or
    amortized, but remains valid even if structures are shared.
    .
    /Security/
    .
    This package currently provides no defenses against hash collision attacks
    such as HashDoS.
    Users who need to store input from untrusted sources are advised to use
    @Data.Map@ or @Data.Set@ from the @containers@ package instead.
category: Data
abi: 7c7d885e1904529becf57c9eb323fb28
exposed: True
exposed-modules:
    Data.HashMap.Internal Data.HashMap.Internal.Array
    Data.HashMap.Internal.List Data.HashMap.Internal.Strict
    Data.HashMap.Lazy Data.HashMap.Strict Data.HashSet
    Data.HashSet.Internal
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/unordered-containers-0.2.19.1
hs-libraries: HSunordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
depends:
    base-4.12.0.0 deepseq-1.4.4.0
    hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN template-haskell-2.14.0.0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/unordered-containers-0.2.19.1/html/unordered-containers.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/unordered-containers-0.2.19.1/html
