name: uuid-types
version: 1.0.5
id: uuid-types-1.0.5-JC6l3EtANxFL1BWuOFs09f
key: uuid-types-1.0.5-JC6l3EtANxFL1BWuOFs09f
license: BSD-3-Clause
copyright: (c) 2017-2018 Herbert Valerio Riedel
           (c) 2008-2014 Antoine Latter
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
author: Antoine Latter
homepage: https://github.com/haskell-hvr/uuid
synopsis: Type definitions for Universally Unique Identifiers
description:
    This library contains type definitions for
    <https://en.wikipedia.org/wiki/UUID Universally Unique Identifiers (UUID)>
    (as specified in
    <http://tools.ietf.org/html/rfc4122 RFC 4122>)
    and basic conversion functions.
    .
    See also the <https://hackage.haskell.org/package/uuid 'uuid' package>
    providing a high-level API for managing the different UUID versions.
category: Data
abi: dd1a251fe2461680f10be6dbb4b6fa29
exposed: True
exposed-modules:
    Data.UUID.Types Data.UUID.Types.Internal
    Data.UUID.Types.Internal.Builder
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/uuid-types-1.0.5-JC6l3EtANxFL1BWuOFs09f
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/uuid-types-1.0.5-JC6l3EtANxFL1BWuOFs09f
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/uuid-types-1.0.5
hs-libraries: HSuuid-types-1.0.5-JC6l3EtANxFL1BWuOFs09f
depends:
    base-4.12.0.0 binary-0.8.6.0 bytestring-0.10.8.2 deepseq-1.4.4.0
    hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
    random-1.2.1.1-6h00GgF0OYj3Bmy1cUaLtz template-haskell-2.14.0.0
    text-1.2.3.1
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/uuid-types-1.0.5/html/uuid-types.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/uuid-types-1.0.5/html
