name: vault
version: 0.3.1.5
id: vault-0.3.1.5-6ZlxayO66uY4blgPimeN4L
key: vault-0.3.1.5-6ZlxayO66uY4blgPimeN4L
license: BSD-3-Clause
copyright: (c) Heinrich Apfelmus 2011-2013
maintainer: Heinrich Apfelmus <apfelmus at quantentunnel de>
author: Heinrich Apfelmus, Elliott Hird
homepage: https://github.com/HeinrichApfelmus/vault
synopsis: a persistent store for values of arbitrary types
description:
    A /vault/ is a persistent store for values of arbitrary types.
    It's like having first-class access to the storage space behind IORefs.
    .
    The data structure is analogous to a bank vault,
    where you can access different bank boxes with different keys;
    hence the name.
    .
    Also provided is a /locker/ type, representing a store for a single element.
category: Data
abi: a7e79f2e0d9bd1eb5c05fb44800278ed
exposed: True
exposed-modules:
    Data.Unique.Really Data.Vault.Lazy Data.Vault.ST.Lazy
    Data.Vault.ST.Strict Data.Vault.Strict
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/vault-0.3.1.5-6ZlxayO66uY4blgPimeN4L
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/vault-0.3.1.5-6ZlxayO66uY4blgPimeN4L
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/vault-0.3.1.5
hs-libraries: HSvault-0.3.1.5-6ZlxayO66uY4blgPimeN4L
depends:
    base-4.12.0.0 containers-0.6.0.1
    hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
    unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/vault-0.3.1.5/html/vault.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/vault-0.3.1.5/html
