name: vector-stream
version: 0.1.0.0
id: vector-stream-0.1.0.0-L7E6bUqBUZfHSRRThdJYDL
key: vector-stream-0.1.0.0-L7E6bUqBUZfHSRRThdJYDL
license: BSD-3-Clause
copyright: (c) Roman Leshchinskiy 2008-2012
           Alexey Kuleshevich 2020-2022,
           Aleksey Khudyakov 2020-2022,
           Andrew Lelechenko 2020-2022
maintainer: Haskell Libraries Team <libraries@haskell.org>
author: Roman Leshchinskiy <rl@cse.unsw.edu.au>
homepage: https://github.com/haskell/vector
synopsis: Efficient Streams
description:
    Simple yet powerful monadic streams that are used
    as a backbone for vector package fusion functionality.
category: Data, Data Structures
abi: e8bbd0fb7bbae6c4012f8b4b06b8dda5
exposed: True
exposed-modules:
    Data.Stream.Monadic
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/vector-stream-0.1.0.0-L7E6bUqBUZfHSRRThdJYDL
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/vector-stream-0.1.0.0-L7E6bUqBUZfHSRRThdJYDL
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/vector-stream-0.1.0.0
hs-libraries: HSvector-stream-0.1.0.0-L7E6bUqBUZfHSRRThdJYDL
depends:
    base-4.12.0.0 ghc-prim-0.5.3
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/vector-stream-0.1.0.0/html/vector-stream.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/vector-stream-0.1.0.0/html
