name: wai-logger
version: 2.4.0
id: wai-logger-2.4.0-IV31P5svvxp33MkSML2YV3
key: wai-logger-2.4.0-IV31P5svvxp33MkSML2YV3
license: BSD-3-Clause
maintainer: Kazu Yamamoto <kazu@iij.ad.jp>
author: Kazu Yamamoto <kazu@iij.ad.jp>
synopsis: A logging system for WAI
description:
    A logging system for WAI
category: Web, Yesod
abi: 713119764c3ceb44e19053deadec54ae
exposed: True
exposed-modules:
    Network.Wai.Logger
hidden-modules: Network.Wai.Logger.Apache Network.Wai.Logger.IP
                Network.Wai.Logger.IORef
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/wai-logger-2.4.0-IV31P5svvxp33MkSML2YV3
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/wai-logger-2.4.0-IV31P5svvxp33MkSML2YV3
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/wai-logger-2.4.0
hs-libraries: HSwai-logger-2.4.0-IV31P5svvxp33MkSML2YV3
depends:
    base-4.12.0.0 byteorder-1.0.4-IVStE0plZAH4UpHo5zwztw
    bytestring-0.10.8.2 fast-logger-3.1.1-yKTYa5XreaK1TuiJqvQH
    http-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
    network-3.1.2.7-IgDwoKKAASu5MMqcFhn6CW
    wai-3.2.3-19bZxcKRjkP7d744tVcD0t
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/wai-logger-2.4.0/html/wai-logger.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/wai-logger-2.4.0/html
