name: wai-app-static
version: 3.1.7.4
id: wai-app-static-3.1.7.4-BcoZ9eDwp8N64Z2jehnyp2
key: wai-app-static-3.1.7.4-BcoZ9eDwp8N64Z2jehnyp2
license: MIT
maintainer: Michael Snoyman <michael@snoyman.com>, Greg Weber <greg@gregweber.info>
author: Michael Snoyman <michael@snoyman.com>
stability: Stable
homepage: http://www.yesodweb.com/book/web-application-interface
synopsis: WAI application for static serving
description:
    API docs and the README are available at <http://www.stackage.org/package/wai-app-static>.
category: Web, Yesod
abi: 793e377b7ab153fa75d8dd36d87abebc
exposed: True
exposed-modules:
    Network.Wai.Application.Static WaiAppStatic.CmdLine
    WaiAppStatic.Listing WaiAppStatic.Storage.Embedded
    WaiAppStatic.Storage.Filesystem WaiAppStatic.Types
hidden-modules: Util WaiAppStatic.Storage.Embedded.Runtime
                WaiAppStatic.Storage.Embedded.TH
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/wai-app-static-3.1.7.4-BcoZ9eDwp8N64Z2jehnyp2
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/wai-app-static-3.1.7.4-BcoZ9eDwp8N64Z2jehnyp2
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/wai-app-static-3.1.7.4
hs-libraries: HSwai-app-static-3.1.7.4-BcoZ9eDwp8N64Z2jehnyp2
depends:
    base-4.12.0.0 blaze-html-0.9.1.2-CmY61JTVubqHXooOILzCtJ
    blaze-markup-0.8.2.8-La34AetGdrgBfbDxaNOhLH bytestring-0.10.8.2
    containers-0.6.0.1 cryptonite-0.29-E6eup9ojG2WJgRYysXdUD1
    directory-1.3.3.0 file-embed-0.0.15.0-A43Ro76atEZFJsfCfxS3gh
    filepath-1.4.2.1 http-date-0.0.11-KviULUeBaxoxCjoIQXxrL
    http-types-0.12.3-IBjgjss3zdv9qPM5LtYD96
    memory-0.17.0-B4oCfvxykobLSIFpq5HVDY
    mime-types-0.1.0.9-IuKFWuzgmF26e9nOlDWqrD
    old-locale-1.0.0.7-D4Rn5zPhtMJBwwirPJNu78
    optparse-applicative-0.17.0.0-7AYOrtajhQJAKUIgKJAsoT
    template-haskell-2.14.0.0 text-1.2.3.1 time-1.8.0.2
    transformers-0.5.6.2 unix-compat-0.6-DsZOczkYwBC8eXogTONDW9
    unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
    wai-3.2.3-19bZxcKRjkP7d744tVcD0t
    wai-extra-3.1.12.1-JasMgWqGX6oJuCfRCGvxTS
    warp-3.3.21-JANt0L0LHzc53EnCD5hLMt
    zlib-0.6.2-BdOecmQ0rL1HOiGypdSgxY
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/wai-app-static-3.1.7.4/html/wai-app-static.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/wai-app-static-3.1.7.4/html
