name: witherable
version: 0.4.2
id: witherable-0.4.2-FTJsoTFWi6bKd5fGuW0R8
key: witherable-0.4.2-FTJsoTFWi6bKd5fGuW0R8
license: BSD-3-Clause
copyright: Copyright (c) 2014 Fumiaki Kinoshita
maintainer: Fumiaki Kinoshita <fumiexcel@gmail.com>
author: Fumiaki Kinoshita
homepage: https://github.com/fumieval/witherable
synopsis: filterable traversable
description:
    A stronger variant of `traverse` which can remove elements and generalised mapMaybe, catMaybes, filter
category: Data
abi: ac9177ab6aeb883cb58c2e193c54d0a8
exposed: True
exposed-modules:
    Data.Witherable Witherable
import-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/witherable-0.4.2-FTJsoTFWi6bKd5fGuW0R8
library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5/witherable-0.4.2-FTJsoTFWi6bKd5fGuW0R8
dynamic-library-dirs: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/lib/x86_64-linux-ghc-8.6.5
data-dir: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/x86_64-linux-ghc-8.6.5/witherable-0.4.2
hs-libraries: HSwitherable-0.4.2-FTJsoTFWi6bKd5fGuW0R8
depends:
    base-4.12.0.0 base-orphans-0.8.6-5O5jqEW3stE4CAsm1Catjq
    containers-0.6.0.1 hashable-1.4.0.2-45679OrlPvpJEGb1I6x7iN
    indexed-traversable-0.1.2-9akKdFoyxR68aS3W4yhwtK
    indexed-traversable-instances-0.1.1-uCyJVgG0I58WGFJhUChUG
    transformers-0.5.6.2
    unordered-containers-0.2.19.1-6VSXdlErO69DIW6OK9WyL0
    vector-0.13.0.0-EY1ezPeV6x5EBOONBzdfse
haddock-interfaces: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/witherable-0.4.2/html/witherable.haddock
haddock-html: /mnt/c/Users/n.nguyen/OneDrive/FP/Sudoku/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.6.5/witherable-0.4.2/html
